apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  namespace: jenkins-demo

spec:
  type: LoadBalancer

  selector:
    app: jenkins-demo

  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP